spring:
   mail:
    host: smtp.gmail.com
    port: 587
    username: sochusttest@gmail.com
    password: soch2020
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: false
      hibernate:
         ddl-auto: none
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: false
   datasource:
       type: com.zaxxer.hikari.HikariDataSource
       #dataSourceClassName: org.postgresql.Driver
       url: jdbc:postgresql://10.247.185.10:5432/soch_train_app_db?currentSchema=soch
       username: soch_train_app_user
       password: S0chApP2020
       hikari:
        poolName: Hikari
logging:
   level:
       root: error
       org: error
       gov: error
twilio:
       sid: AC5af9c36150f95f44138367a93b8f9d3f
       token: 06756371869d5b07e1358af6b2cf6cb0
       smsnumber: "+12513337971"
       whatsappnumber: "+14155238886"
accessKey: $5gw@965
crossDomainAllowedOrigins: https://sochtraining.naco.gov.in
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=
notificationSmsApiEndpoint: https://dummyurl/dummyurl/dummyurl
notificationSmsApiUsername: dummyuser
notificationSmsApiPin: dummypin
notificationSmsApiSignature: SENDERID
