spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: false
   datasource:
       dataSourceClassName: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/soch-db-dev?currentSchema=soch
       username: postgres
       password: postgres
logging:
   level:
       root: INFO
       org.springframework: INFO
       com.naco.soch: INFO
       org.hibernate: INFO
twilio:
       sid: AC06bf9a190b603076e7b228119042087e
       token: 888ef6252b95646ffbbed63049714672
       smsnumber: "+12018014539"
       whatsappnumber: "+14155238886"